site_name: Essensys Support Site Docs
theme:
  name: material
  palette:
    primary: teal
    accent: purple

nav:
  - Home: index.md
  - Features:
    - User Profile & Devices: features.md
    - Authentication: authentication.md
    - Roles & Permissions: roles_matrix.md
    - Audit Trail: audit_trail.md
  - Configuration: configuration.md
